DEEPSORT:
  MODEL_TYPE: "osnet_x_25"
  MAX_DIST: 1 # The matching threshold. Samples with larger distance are considered an invalid match
  MAX_IOU_DISTANCE: 0.7 # Gating threshold. Associations with cost larger than this value are disregarded.
  MAX_AGE: 300 # Maximum number of missed misses before a track is deleted
  N_INIT: 1 # Number of frames that a track remains in initialization phase
  NN_BUDGET: 100 # Maximum size of the appearance descriptors gallery
  
